[package]
name = "mhs"
version = "0.1.0"
authors = ["zjohnson"]
edition = "2018"

[dependencies]
# HTTP CLIENT
reqwest = "0.9.18"

#HTML Parser and Querier
select = "0.4.3"

regex = "1.3.1"

serde_json = "1.0"

lazy_static = "1.4.0"
